#!/bin/sh

dir="$HOME/dotfiles/Utilites/ASM/."
cp "$2" "$dir"
file=$(basename "$2" .asm)

while getopts "c:e" opt; do
  case $opt in
    c) dosbox -c "mount C $dir" -c "C:" -c "startCom $file" ;;
    e) dosbox -c "mount C $dir" -c "C:" -c "startExe $file" ;;
    \?) echo "Unknown flag"; exit 1;;
  esac
done
