# preload = /home/gohy/.config/hypr/background.jpg
# wallpaper = ,/home/gohy/.config/hypr/background.jpg


wallpaper {
monitor = eDP-1
# path = ~/.config/hypr/wallpaper.jpg
# path = ~/.config/hypr/jpg
path = ~/.config/hypr/wallpapers/
order = random
fit_mode = cover
timeout = 3600
}
