#!/bin/bash

case "$1" in
    scan)
        sum=0
        for n in $(find ~ -name "target" -type d -print0 2>/dev/null | xargs -0 du --exclude=. -sh -BM | cut -d'M' -f1); do
            ((sum += n))
        done
        find ~ -name "target" -type d -exec du -sh -BM {} \; 2>/dev/null 
        echo "$sum мегабайтов занято папками target"
        ;;
    rm)
        dirs="$(find ~ -name "target" -type d 2>/dev/null)"
        if [[ $? -eq 0 ]]; then
            rm -r "$dirs"
        fi
        ;;
esac
